python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_100 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-100.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_100 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-100.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_200 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-200.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_200 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-200.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_500 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-500.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_500 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-500.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_1000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-1000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_1000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-1000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_2000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-2000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_2000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-2000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_3000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-3000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_3000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-3000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_4000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-4000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_4000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-4000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_5000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-5000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_5000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-5000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_6000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-6000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_6000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-6000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_7000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-7000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_7000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-7000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_8000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-8000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_8000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-8000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_9000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-9000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_9000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-9000.result
python3 /users/Xinying/YCSB/bin/ycsb load ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_10000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-10000.result
python3 /users/Xinying/YCSB/bin/ycsb run ozonedb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_10000 > /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-10000.result

python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_100 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-100.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_100 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-100.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_200 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-200.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_200 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-200.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_500 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-500.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_500 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-500.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_1000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-1000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_1000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-1000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_2000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-2000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_2000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-2000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_3000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-3000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_3000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-3000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_4000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-4000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_4000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-4000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_5000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-5000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_5000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-5000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_6000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-6000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_6000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-6000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_7000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-7000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_7000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-7000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_8000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-8000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_8000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-8000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_9000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-9000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_9000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-9000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb load rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_10000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-10000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data
python3 /users/Xinying/YCSB/bin/ycsb run rocksdb -s -P /users/Xinying/ozonedb/bench/ycsb/workload/workloada/workloada_10000 > /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-10000.result -p rocksdb.dir=/tank/ycsb-rocksdb-data

bash ycsb2graph.sh /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-100.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-200.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-500.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-1000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-2000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-3000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-4000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-5000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-6000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-7000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-8000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-9000.result /users/Xinying/ozonedb/bench/ycsb/ozonedb-WorkloadA-10000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-100.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-200.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-500.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-1000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-2000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-3000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-4000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-5000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-6000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-7000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-8000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-9000.result /users/Xinying/ozonedb/bench/ycsb/rocksdb-WorkloadA-10000.result